In [1]:
import pandas as pd

In [51]:
df = pd.read_csv('TLKM.JK.csv', parse_dates=['Date'])
df.head()
df.dtypes
# df.head(1)
# df.loc[0]

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [21]:
df[
    df['Close'] == 
    df['Close'].max()
]

          Date    Open    High     Low   Close  Adj Close     Volume
0   2019-06-05  3900.0  3900.0  3900.0  4470.0     3900.0          0
1   2019-06-06  3900.0  3900.0  3900.0  4470.0     3900.0          0
2   2019-06-07  3900.0  3900.0  3900.0  4470.0     3900.0          0
3   2019-06-10  4000.0  4060.0  3970.0  4470.0     4040.0  222522800
4   2019-06-11  4010.0  4060.0  4000.0  4470.0     4020.0   88861700
5   2019-06-12  3880.0  3950.0  3840.0  4470.0     3940.0  134724400
6   2019-06-13  3940.0  3990.0  3900.0  4470.0     3990.0  115734700
7   2019-06-14  4020.0  4050.0  3970.0  4470.0     3990.0   92466800
8   2019-06-17  3950.0  3970.0  3900.0  4470.0     3900.0   60851700
9   2019-06-18  3890.0  3990.0  3890.0  4470.0     3980.0   66112800
10  2019-06-19  4020.0  4120.0  4020.0  4470.0     4100.0  100210400
11  2019-06-20  4110.0  4110.0  4020.0  4470.0     4040.0   57673700
12  2019-06-21  4010.0  4040.0  3950.0  4470.0     4040.0  154049700
13  2019-06-24  4050.0  4050.0  3970.0  4470.0     3980.0   50525100
14  2019-06-25  4040.0  4040.0  4000.0  4470.0     4010.0   42601100
15  2019-06-26  4020.0  4050.0  3980.0  4470.0     3980.0   56092200
16  2019-06-27  4010.0  4120.0  4000.0  4470.0     4090.0   94221200
17  2019-06-28  4100.0  4200.0  4090.0  4470.0     4140.0  130153100
18  2019-07-01  4200.0  4240.0  4170.0  4470.0     4220.0   79382300
19  2019-07-02  4240.0  4250.0  4180.0  4470.0     4250.0   87999800
20  2019-07-03  4160.0  4240.0  4160.0  4470.0     4240.0   63296200
21  2019-07-04  4190.0  4260.0  4190.0  4470.0     4250.0   38459300
22  2019-07-05  4260.0  4280.0  4240.0  4470.0     4280.0   50332800
23  2019-07-08  4230.0  4290.0  4210.0  4470.0     4270.0   57903400
24  2019-07-09  4300.0  4370.0  4270.0  4470.0     4350.0  124822400
25  2019-07-10  4310.0  4320.0  4260.0  4470.0     4290.0   62529900
26  2019-07-11  4250.0  4280.0  4240.0  4470.0     4270.0   25645900
27  2019-07-12  4240.0  4250.0  4170.0  4470.0     4180.0   57088600
28  2019-07-15  4250.0  4290.0  4230.0  4470.0     4280.0   66960500
29  2019-07-16  4240.0  4280.0  4210.0  4470.0     4240.0   45461500
..         ...     ...     ...     ...     ...        ...        ...
103 2019-10-28  4280.0  4280.0  4220.0  4470.0     4260.0   30710600
104 2019-10-29  4230.0  4330.0  4220.0  4470.0     4330.0   68715000
105 2019-10-30  4290.0  4350.0  4210.0  4470.0     4270.0   89575600
106 2019-10-31  4220.0  4240.0  4080.0  4470.0     4110.0  185713300
107 2019-11-01  4090.0  4150.0  4060.0  4470.0     4080.0  107208500
108 2019-11-04  4080.0  4160.0  4080.0  4470.0     4150.0   65897700
109 2019-11-05  4170.0  4200.0  4130.0  4470.0     4200.0  109276000
110 2019-11-06  4180.0  4190.0  4110.0  4470.0     4120.0  134618700
111 2019-11-07  4150.0  4150.0  3990.0  4470.0     4070.0  125291200
112 2019-11-08  4010.0  4120.0  3990.0  4470.0     4110.0   70404800
113 2019-11-11  4040.0  4120.0  4040.0  4470.0     4100.0   57079800
114 2019-11-12  4050.0  4190.0  4050.0  4470.0     4180.0   88251100
115 2019-11-13  4130.0  4170.0  4100.0  4470.0     4150.0   91925700
116 2019-11-14  4110.0  4130.0  4010.0  4470.0     4050.0  123468500
117 2019-11-15  4080.0  4090.0  4030.0  4470.0     4080.0   50780500
118 2019-11-18  4040.0  4060.0  3990.0  4470.0     4000.0  104978700
119 2019-11-19  4000.0  4020.0  3970.0  4470.0     4020.0  113996600
120 2019-11-20  4000.0  4090.0  4000.0  4470.0     4090.0  149185500
121 2019-11-21  4050.0  4090.0  4020.0  4470.0     4020.0   64005900
122 2019-11-22  4030.0  4050.0  4000.0  4470.0     4050.0   76569400
123 2019-11-25  4070.0  4070.0  3940.0  4470.0     3950.0  107581200
124 2019-11-26  3950.0  3960.0  3860.0  4470.0     3860.0  281002600
125 2019-11-27  3870.0  3930.0  3800.0  4470.0     3880.0   97511300
126 2019-11-28  3830.0  3900.0  3800.0  4470.0     3820.0   70635000
127 2019-11-29  3860.0  3950.0  3840.0  4470.0     3930.0   72146900
128 2019-12-02  3960.0  3960.0  3930.0  4470.0     3950.0   74263500
129 2019-12-03  3920.0  3940.0  3910.0  4470.0     3920.0   74494000
130 2019-12-04  3920.0  3990.0  3900.0  4470.0     3990.0   64948300
131 2019-12-05  3990.0  4080.0  3990.0  4470.0     4060.0  118494800
132 2019-12-06  4040.0  4100.0  4020.0  4470.0     4100.0   50682100

[133 rows x 7 columns]

In [72]:
# contoh resample data
# df = df.set_index('Date')
df.head()

# mencari data perakhir bulan (M)
# mencari data perakhir minggu (W)
# mencari perkuartil (Q) per 3bulan 
# mencari pertahun (Y)
df['2019-09':'2019-11']['Close'].resample('Q').mean()

Date
2019-09-30    4266.666667
2019-12-31    4125.681818
Freq: Q-DEC, Name: Close, dtype: float64

In [80]:
# mengatasi hari yang hiang ketika ada sabtu dan minggu libur

# 1. membuat data menjadi berurutan
df = df.sort_index()
df

#. 2. mengisi hari2 yang rumpang dengan NaN
df1 = df.resample('D').sum()
df1.head(10)
import numpy as np
[df1['Volume'] == np.nan]

[Date
 2019-06-05    False
 2019-06-06    False
 2019-06-07    False
 2019-06-08    False
 2019-06-09    False
 2019-06-10    False
 2019-06-11    False
 2019-06-12    False
 2019-06-13    False
 2019-06-14    False
 2019-06-15    False
 2019-06-16    False
 2019-06-17    False
 2019-06-18    False
 2019-06-19    False
 2019-06-20    False
 2019-06-21    False
 2019-06-22    False
 2019-06-23    False
 2019-06-24    False
 2019-06-25    False
 2019-06-26    False
 2019-06-27    False
 2019-06-28    False
 2019-06-29    False
 2019-06-30    False
 2019-07-01    False
 2019-07-02    False
 2019-07-03    False
 2019-07-04    False
               ...
 2019-11-07    False
 2019-11-08    False
 2019-11-09    False
 2019-11-10    False
 2019-11-11    False
 2019-11-12    False
 2019-11-13    False
 2019-11-14    False
 2019-11-15    False
 2019-11-16    False
 2019-11-17    False
 2019-11-18    False
 2019-11-19    False
 2019-11-20    False
 2019-11-21    False
 2019-11-22    False
 2019-11-23    False
 2019-11-24    False
 2019-11-25    False
 2019-11-26    False
 2019-11-27    False
 2019-11-28    False
 2019-11-29    False
 2019-11-30    False
 2019-12-01    False
 2019-12-02    False
 2019-12-03    False
 2019-12-04    False
 2019-12-05    False
 2019-12-06    False
 Freq: D, Name: Volume, Length: 185, dtype: bool]

In [69]:
df2 = df1.fillna(method='ffill', axis=0)
df2.head(10)

              Open    High     Low   Close  Adj Close       Volume
Date
2019-06-05  3900.0  3900.0  3900.0  3900.0     3900.0          0.0
2019-06-06  3900.0  3900.0  3900.0  3900.0     3900.0          0.0
2019-06-07  3900.0  3900.0  3900.0  3900.0     3900.0          0.0
2019-06-08  3900.0  3900.0  3900.0  3900.0     3900.0          0.0
2019-06-09  3900.0  3900.0  3900.0  3900.0     3900.0          0.0
2019-06-10  4000.0  4060.0  3970.0  4040.0     4040.0  222522800.0
2019-06-11  4010.0  4060.0  4000.0  4020.0     4020.0   88861700.0
2019-06-12  3880.0  3950.0  3840.0  3940.0     3940.0  134724400.0
2019-06-13  3940.0  3990.0  3900.0  3990.0     3990.0  115734700.0
2019-06-14  4020.0  4050.0  3970.0  3990.0     3990.0   92466800.0